### ISSUE TITLE
AttributeError: 'SkypeForBusinessBot' object has no attribute 'url_oauth'

### ISSUE THREAD

**Issue by souravchaterjee** [dadecoza/rasa-s4b-channel#1]
Hi Buddy, thank you for the precious code. Saved time, I am getting the error "AttributeError: 'SkypeForBusinessBot' object has no attribute 'url_oauth'" when I try run the connector. Any help is highly appreciated!

**Comment by souravchaterjee** [comment]
Went past this by changing ucwa to lyncdiscoveryinternal, however met with ssl verify error on python 3.6.8. Added verify=FALSE in code. Now getting the following error:

################################
  <h2>502 - Web server received an invalid response while acting as a gateway or proxy server.</h2>
  <h3>There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.</h3>
#################################


Seems the https call and subsequent http call back to rasa server is causing an issue

**Comment by souravchaterjee** [comment]
More information:

Traceback (most recent call last):
  File "rasa_skype4B_channel.py", line 375, in <module>
    main(sys.argv[1:])
  File "rasa_skype4B_channel.py", line 369, in main
    bot = SkypeForBusinessBot(discovery_url, username, password)
  File "rasa_skype4B_channel.py", line 285, in __init__
    self.setup_application()
  File "rasa_skype4B_channel.py", line 129, in setup_application
    self.url_messaging = self.url_root+j['_embedded']['communication']['_links']['startMessaging']['href']

**Comment by dadecoza** [comment]
are you behind a corporate proxy?

**Comment by souravchaterjee** [comment]
Yes in a corporate environment, however without proxy setting, direct access to the discovery server works fine.

**Comment by dadecoza** [comment]
line 66

```python
def fix_url(self, url):
        return re.sub(r'^(https?://.*?)/', self.url_root, url)
```

change to

```python 
def fix_url(self, url):
        return url
```

and test again please

**Comment by souravchaterjee** [comment]
Getting this error now:

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='skypeweb.eu.internal.com', port=443): Max retries exceeded with url: /Autodiscover/AutodiscoverService.svc/root/oauth/user?originalDomain=internal.com (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000019B1AE39EB8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

**Comment by souravchaterjee** [comment]
Can this be since the SSL connection is not trusted. Added the default certificate to the PEM file, but somehow it doesn't work. so had to force verify=FALSE
Thanks for your help!

**Comment by dadecoza** [comment]
sorry that fix i gave you made it worse.  let me try something quick ...

**Comment by dadecoza** [comment]
line 117
after ...
```python
self.url_application = url
```

add

```python
m = re.search('^(https://.*?)/', self.url_application)
self.url_root = m.group(1)
```

**Comment by souravchaterjee** [comment]
hey thanks! You are very kind, let me try!

**Comment by souravchaterjee** [comment]
Sorry same error, can I use a workaround or something. You suspect a proxy blocking this?

**Comment by souravchaterjee** [comment]
When I change the discovery server port from 443 to 4443, the behavior changes to as below:


####################################
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='skypeweb.eu.amdocs.com', port=443): Max retries exceeded with url: /Autodiscover/AutodiscoverService.svc/root/oauth/user?originalDomain=amdocs.com (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002138D1C8EB8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

**Comment by dadecoza** [comment]
If you do have a proxy you can change line 365 to look like ...
```python
bot = SkypeForBusinessBot(discovery_url, username, password, proxy={"https_proxy": "http://yourcompany.proxy.com:80/"})
```

**Comment by souravchaterjee** [comment]
hey thanks.. Did set the proxy on command line, doesn't help.
the above option gives - 
##############
raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments
##############

Will check further.

**Comment by souravchaterjee** [comment]
Hi Dadecoza, Need help in understanding this one. Is it failing in connecting to the second server post discovery? Can you let me know that from the snippet? Asking since the  warnings convey that 1st few calls seem to be going through.

########################################
import 'shlex' # <_frozen_importlib_external.SourceFileLoader object at 0x000001E275539240>
import 'netrc' # <_frozen_importlib_external.SourceFileLoader object at 0x000001E275529CF8>
C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3
.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3
.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3
.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3
.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3
.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3
.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "rasa_skype4B_channel.py", line 375, in <module>
    main(sys.argv[1:])
  File "rasa_skype4B_channel.py", line 369, in main
    bot = SkypeForBusinessBot(discovery_url, username, password)
  File "rasa_skype4B_channel.py", line 285, in __init__
    self.setup_application()
  File "rasa_skype4B_channel.py", line 129, in setup_application
    self.url_messaging = self.url_root+j['_embedded']['communication']['_links']['startMessaging']['href']
KeyError: '_embedded'

**Comment by souravchaterjee** [comment]
Looks like the local connection request to the Skype server is failing as the IP is not known. Browser works however.

**Comment by souravchaterjee** [comment]
Hi,

With access to both discovery server(lyncdiscover.internal.com) and skypeweb.eu.internal.com, still getting the below http 500 with the first modification suggested. Seems a change in error.

C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3
.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3
.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3
.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3
.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3
.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3
.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "rasa_skype4B_channel.py", line 375, in <module>
    main(sys.argv[1:])
  File "rasa_skype4B_channel.py", line 369, in main
    bot = SkypeForBusinessBot(discovery_url, username, password)
  File "rasa_skype4B_channel.py", line 285, in __init__
    self.setup_application()
  File "rasa_skype4B_channel.py", line 129, in setup_application
    self.url_messaging = self.url_root+j['_embedded']['communication']['_links']['startMessaging']['href']
KeyError: '_embedded'

##################

  <h2>500 - Internal server error.</h2>
  <h3>There is a problem with the resource you are looking for, and it cannot be displayed.</h3>

**Comment by souravchaterjee** [comment]
More information about this one- 

<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>500 - Internal server error.</h2>
  <h3>There is a problem with the resource you are looking for, and it cannot be displayed.</h3>
 </fieldset></div>
</div>

**Comment by souravchaterjee** [comment]
Kindly note this response is coming with the 1st setting you suggested.(below) It was different earlier since the connection was not going through. With proper proxy it is going out now:

_________________________________________________________________________
line 66

def fix_url(self, url):
        return re.sub(r'^(https?://.*?)/', self.url_root, url)
change to

def fix_url(self, url):
        return url
________________________________________________________________________________

**Comment by souravchaterjee** [comment]
Check this - https://blogs.technet.microsoft.com/poptart/2015/02/09/ucwa-sign-in-fails-while-seeing-http-options-request/

**Comment by souravchaterjee** [comment]
Put print statements to check the flow here: 
https://ucwa.skype.com/documentation/keytasks-createapplication
The application server zone was moved to fix this alongwith the line 66 change suggested.

**Comment by dadecoza** [comment]
Did you get it to work?

**Comment by arunthiagarajan1988** [comment]
Hi Dadecoza, I'm trying to run inside my office premises ...would it work ? Could you pls help me more as i am not able to debug the errors.

**Comment by souravchaterjee** [comment]
> Did you get it to work?

Yes, simply asked IT to switch zones and with one of them it worked!
this script however times out and exits. Timeout can be increased at most to 1800
